# ===============================================
# Secção 1: Credenciais do e-mail para envio de notificações
# Utilizado pela função de envio de e-mail em retirada.py
# ===============================================
[email]
username = "dadositajr.apps@gmail.com"
password = "ucpvjziykcrvosmu"

# ===============================================
# Secção 2: Dados da sua empresa para personalizar os e-mails
# ===============================================
[empresa]
pix = "suachavepix@dominio.com"
nome = "ITA Júnior"

# ===============================================
# Secção 3: Credenciais para aceder à Planilha Google
# Lidas pelo arquivo conexao.py para buscar e atualizar os dados.
# Este é o conteúdo do seu ficheiro JSON.
# ===============================================
[google_sheets_credentials]
type = "service_account"
project_id = "biblioteca-jr"
private_key_id = "7ffebd73cc9fa31f3ef28fc49c9f37b750671bf1"
# Usamos aspas triplas para preservar a formatação da chave privada com várias linhas
private_key = """-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDU+O7u5vJlPUfY\nsdad5BK9Ajs3sx3QSxkxAK4jIgNj4yEruYpH3A6SrcKPWgSwkMHvj6I1EKPKgl3x\nLJgEXwN9rl6MzjqpUCbGeKda5L36s9p8sVvH9w/WCy/seq/AyRpYtnH89hAWgsb+\nWwLAC3ATzjGmt0j/MaH5PXPYkPCgfMTBmzvAsGDkbRLFub7vgcVLoCRd57cEahHG\nTdz9bzAPdJFSWOC/+24Yry+rFivhoGhKyECM2wEFf27p2UM8IkfFQzlxKek7NVc/\nOmgg+XGQRLVh/WUQtZjBDsil9TAtRMPn41e/evuO876JYAuGex8/gz4C8tBZEKnq\nfGIdz5NJAgMBAAECggEAAmZdtuZ2U8q5fQkf/H598ZBNX4bOrrKx8Xnq/G1dMWp1\nTLtWAhJKPb/kgd4HUIAJF2x8bPGnjtgiO93/RolVjjyBRz/prE/BaBoi9KTAOUt+\nikorWRkBHi3ZF+aYBWmeuOIxbaLOMpq9qE8ZPFXEqQx5RcIp+eoyw468N/QGKiDI\niEdGdlNgdNaWEZoENtZa61PZ19DW5rBo+Leg1K/hiofmJzW1sxNi32chbLlqDvmw\nm4SBIlqML+1R5j+dZWhgLhM7yl1o8FlnHsWmebCWZ+283zFd4xheABTKMsdlisSP\nJLhC4yD+tnl/14Es2syoXysAMyvNEwU2hgPzTk6OcwKBgQD0PxeB8g6ObzXsMEQp\ng8gxRcgLpXdFFzahGtmYPwb2VmjfHHWwujbsVu6tVEvGSrHcumvwXkoke/IyaxOr\nza8Dvc47J4mcMhM4W7MCUhOS6WyQKqlZQEMwoamoUk5O7VeFVbf0iaXt9R8F/8V6\nPUuJpOVVpRmHkJyNs+IEZIGNHwKBgQDfOJJf/XxJSKgEX7MBGxrlxMD8PMu2NNlt\n2jeWnewL0ouLsdyh+JCzZpUQg+kmiaxOe1l8xoIdXpCW8l/Mzrlugrh2imFHZkNo\n1m+RBXkphbCF9IQHfoy4CwP3vru9qUXYCiSXPuLM9iOlpM9OkJdYp3ys21XRxWhP\nF2nlsbnqlwKBgFyPXFU+ag3IT2MGl440BrXFgB4Jwr1IIsfC6RstJ3JLJMsIegFT\nUGUYPLMq8txeijDf5O/ei7Jv1kUNFxNQizabw3/fZ+LthyMgfSIwAIL4OtAXmr3c\nAJp5aVYEevCmOTiqV2AwmdUnw23+k9PTTsEG4HIocxhQ0UNSHCEWBZJ5AoGBAMHf\nCIKGTmP3zrW9yGK1f+7/q/1ncCaYUB+w34bZMiIygzCZEd87W7H07pKhfuYRvK2N\nRHOylV+cukffyoS/Jx5sOnn6RfMVRobPd6ak8k615lLxw5oet2lBZ/jMl5Jqalbw\nuEcEP0d0oBFFyyeZPVmqXgZjmW3P3oCS/U6ZxbeRAoGAZ7F6yFO30IcDt9qaWwhM\nZ6gZAG0X2q6cK3kHmIssdr158ZYjolprXtFS2bzFGXVmtlIUDW9r5yGmXL+4t38c\nDPAmIovrppI/GOqrrX7kfRpDLwxepMmI5bJwToaithZMdNeVLSiwPErtSVaxyJdi\n4GT5+YN4mqbtb5waYiYgBmI=\n-----END PRIVATE KEY-----"""
client_email = "biblioteca-jr@biblioteca-jr.iam.gserviceaccount.com"
client_id = "100259191829511286469"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/biblioteca-jr%40biblioteca-jr.iam.gserviceaccount.com"
